// Generated by gencpp from file action_demo/LinewalkFeedback.msg
// DO NOT EDIT!


#ifndef ACTION_DEMO_MESSAGE_LINEWALKFEEDBACK_H
#define ACTION_DEMO_MESSAGE_LINEWALKFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_demo
{
template <class ContainerAllocator>
struct LinewalkFeedback_
{
  typedef LinewalkFeedback_<ContainerAllocator> Type;

  LinewalkFeedback_()
    : processing(0.0)  {
    }
  LinewalkFeedback_(const ContainerAllocator& _alloc)
    : processing(0.0)  {
  (void)_alloc;
    }



   typedef float _processing_type;
  _processing_type processing;





  typedef boost::shared_ptr< ::action_demo::LinewalkFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_demo::LinewalkFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct LinewalkFeedback_

typedef ::action_demo::LinewalkFeedback_<std::allocator<void> > LinewalkFeedback;

typedef boost::shared_ptr< ::action_demo::LinewalkFeedback > LinewalkFeedbackPtr;
typedef boost::shared_ptr< ::action_demo::LinewalkFeedback const> LinewalkFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_demo::LinewalkFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_demo::LinewalkFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace action_demo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'action_demo': ['/home/yons/develop/AI/V_Slam/sim_platform/devel/.private/action_demo/share/action_demo/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::action_demo::LinewalkFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_demo::LinewalkFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_demo::LinewalkFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_demo::LinewalkFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_demo::LinewalkFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_demo::LinewalkFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_demo::LinewalkFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937db7b3cae0fa8dd17fd3c334ef4852";
  }

  static const char* value(const ::action_demo::LinewalkFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937db7b3cae0fa8dULL;
  static const uint64_t static_value2 = 0xd17fd3c334ef4852ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_demo::LinewalkFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_demo/LinewalkFeedback";
  }

  static const char* value(const ::action_demo::LinewalkFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_demo::LinewalkFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float32 processing\n"
"\n"
;
  }

  static const char* value(const ::action_demo::LinewalkFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_demo::LinewalkFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.processing);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinewalkFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_demo::LinewalkFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_demo::LinewalkFeedback_<ContainerAllocator>& v)
  {
    s << indent << "processing: ";
    Printer<float>::stream(s, indent + "  ", v.processing);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_DEMO_MESSAGE_LINEWALKFEEDBACK_H
